### ISSUE TITLE
@ matching fails when case doesn't match

### ISSUE THREAD

**Issue by csell5** [ThatConference/that-api-sessions#111]
This session isn't auto linking to the community. https://that.us/activities/PLyuT4BCAJhNbM81QsDi I believe it's due to the fact the cases don't match in the description. 

@JavaScript vs @javascript

ref @sojan80

**Comment by brettski** [comment]
> @javascript vs @javascript

They look the same to me.

**Comment by brettski** [comment]
I see the description contains `@JavaScript` which wouldn't match the slug and will. not link the community. 

As a business rule do we want to make everything lowercase before tokenizing?

**Comment by csell5** [comment]
I think so. We can assume the presence of @ in those fields means to associate. But we need to make sure we don't try to match an email address or code.
